runtime: python
env: flex
entrypoint: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
  # Configure your resources based on your needs

manual_scaling:
  instances: 1
  # Or use automatic_scaling

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"